### ISSUE TITLE
You should make Kebab instead

### ISSUE THREAD

**Issue by MattWolf777** [Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8#10]

**Comment by su542sa** [comment]
what is this about? lol

**Comment by 5aled01** [comment]
LOL bro was so disappointed with the code that he gave the op a career advice

**Comment by muh-dirga-f** [comment]
lol

**Comment by GunterWinter** [comment]
i laughed so hard at this lmao

**Comment by Muhammad-Zeerak-Khan** [comment]
Kindly post your concern and the code to reproduce it.

**Comment by su542sa** [comment]
did you not understand
