### ISSUE TITLE
Not Getting Output

### ISSUE THREAD

**Issue by itsAadi1** [Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8#2]
In output video the license plate is not detected. Just the input video is displayed. I think their is problem in trained model. Can you resolve it?

**Comment by Hari-Mutyam** [comment]
Your script main.py has missing test.csv file output write.
Next , visualize.py is not giving the output as per your sample output in the repo.

Attached the output I got.

Please update the codes.
![out mp4](https://github.com/Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8/assets/144352355/138382de-6071-4a13-8f3b-12e28dc662f9)

**Comment by umar-1623** [comment]
File "main.py", line 5, in <module>
    from sort.sort import *
ModuleNotFoundError: No module named 'sort'

**Comment by Muhammad-Zeerak-Khan** [comment]
Please clone the sort repository from here 
https://github.com/abewley/sort

**Comment by Muhammad-Zeerak-Khan** [comment]
@Hari-Mutyam the test_csv is generated by the main.py script. Let the script complete and then run the add_missing_data.py script for the interpolation and better visualization. The interpolated csv should then be passed to the visualize.py for the final output video.

**Comment by Muhammad-Zeerak-Khan** [comment]
@itsAadi1 The trained model is working fine for me. Feel free to train it yourself on the dataset provided in the README.   Let me know if you have further queries.
