### ISSUE TITLE
How many epochs did you train it for the mentioned data ?

### ISSUE THREAD

**Issue by avinashsingh93** [Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8#5]
I need to train this for the dataset you provided. just wanted to know about how many epochs did you train it for the best results ?

**Comment by Muhammad-Zeerak-Khan** [comment]
I trained it for 50 epochs, but now with the newer models, you should be able to get the job done in fewer epochs.
