### ISSUE TITLE
Question: What YoloV8 Task did you use to train the model?

### ISSUE THREAD

**Issue by Blankeos** [Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8#6]
Based on the tasks here: https://docs.ultralytics.com/tasks

Is it?
- Detection
- Pose (with 4 keypoints)
- OBB

I assume it's detection.

I'm looking for a model that can do Pose or OBB to improve the OCR accuracy because OCR usually wants the images to be upright. I think Pose + Warp transformation would help. Or just OBB.

Thanks in advance!

**Comment by Muhammad-Zeerak-Khan** [comment]
I used detection and it worked out well for this case. Would try out the others.
