### ISSUE TITLE
Sort

### ISSUE THREAD

**Issue by Quadwo** [Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8#8]
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from sort.sort import *
ModuleNotFoundError: No module named 'sort'

Error with sort any help?

**Comment by huseyingunes** [comment]
same

**Comment by Mewmul** [comment]
https://github.com/abewley/sort.git this is the sort repository use, I would suggest to use git clone to download
