### ISSUE TITLE
Torch._C not found when I launch main.py

### ISSUE THREAD

**Issue by TheoEI** [Muhammad-Zeerak-Khan/Automatic-License-Plate-Recognition-using-YOLOv8#9]
Hi,
I don't understand, I installed all requirements (their satisfied) but when I launch main.py it tells :    
" import torch._C
ModuleNotFoundError: No module named 'torch._C'"

Any solution ?

**Comment by MattWolf777** [comment]
> Hi, I don't understand, I installed all requirements (their satisfied) but when I launch main.py it tells : " import torch._C ModuleNotFoundError: No module named 'torch._C'"
> 
> Any solution ?

He will never answer...

**Comment by TheoEI** [comment]
OK, thanks for the feedback.
 I'm going to continue my investigation, and if I find a solution I'll share it.

**Comment by Muhammad-Zeerak-Khan** [comment]
Kindly update the environment to python 3.10 and install the requirements. Let me know if you still get the error.

**Comment by shayan-talha** [comment]
> Hi, I don't understand, I installed all requirements (their satisfied) but when I launch main.py it tells : " import torch._C ModuleNotFoundError: No module named 'torch._C'"
> 
> Any solution ?

use numpy version 1.24.3 will resolve the issue.
Step 1 : pip uninstall numpy
Step 2 : add 'numpy=1.24.3' in requirements.txt
Step 3 : pip install -r requirements.txt
